config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'

  draw :api_v1
  draw :admin

  get ':category_alias', to: 'categories#index', as: :category
  get ':category_alias/:child_category_alias', to: 'categories/children#index', as: :child_category
  get ':category_alias/:child_category_alias/:id', to: 'categories/children#show', as: :article



end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  name       :string(191)      not null
#  parent_id  :integer
#  alias      :string(191)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  mount_uploader :thumbnail, CategoryThumbnailUploader

  validates :name, presence: true

  has_many :topics

  def self.get_category_as_json
    Category.all.to_json(only: [:id, :name])
  end

end

app/models/category_form.rb
class CategoryForm
  include ActiveModel::Model

  attr_accessor :name

  def search
    Category.ransack(
        name_cont: self.name
    ).result
  end

end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController

    def index
      @category = Category.new
      if params[:category_form].present?
        @category_form = CategoryForm.new(category_form_params)
        @categories = @category_form.search.order(id: 'DESC').page(params[:page])
      else
        @category_form = CategoryForm.new
        @categories = Category.order(id: 'DESC').page(params[:page])
      end
    end


    def show
    end

    def new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: '保存に成功しました。'
      else
        flash[:alert] = '保存に失敗しました。'
        redirect_to admin_categories_path
      end
    end

    def edit
    end

    def update
      category = Category.find_by!(id: params[:id])
      if category.update(category_params)
        redirect_to admin_categories_path, notice: '変更に成功しました。'
      else
        flash[:alert] = '変更に失敗しました。'
        redirect_to admin_categories_path
      end
    end

    def destroy
    end

    private

    def category_params
      params.require(:category).permit(
          :name,
          :description,
          :parent_id,
          :alias,
          :thumbnail

      )
    end

    def category_form_params
      params.require(:category_form).permit(
          :name
      )
    end

  end
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < Api::V1::ApplicationController

      def create
        @category = Category.new(category_params)
        if @category.save
          json_response(200, '保存に成功しました。')
        else
          json_response(400, '保存に失敗しました。')
        end
      end

      def update
      end

      def destroy

      end


      private

      def category_params
        params.require(:category).permit(
            :name,
            :description,
            :thumbnail,
            :parent_id,
            :alias
        )
      end
    end
  end
end

app/controllers/categories/children_controller.rb
module Categories
  class ChildrenController < ApplicationController

    def index

    end

    def show
      @topic = Topic.find_by!(id: params[:id])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

  end

end

app/views/categories/_category_new_modal.html.slim
#CategoryNewModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="formModalLabel" style="display: none;"]
  .modal-dialog
    .modal-content
      = form_for @category, url: categories_path, method: :post do |f|
        .category-modal
          .modal-header
            span.close-button[type="button" data-dismiss="modal"] x
          .modal-body
            .form-group
              = f.label :name, class: 'label-main text-small'
              = f.text_field :name, class: 'form-control form-color-main'
            .form-group
              = f.label :description, class: 'label-main text-small'
              = f.text_area :description, class: 'form-control form-color-main'
            .form-group
              = f.label :thumbnail, class: 'label-main text-small'
              = f.file_field :thumbnail, class: 'form-control form-color-main'
            .form-group
              = f.label :parent_id, class: 'label-main text-small'
              = f.collection_select :parent_id, Category.all,  :id, :name, {},  class: 'form-control form-color-main'
            .form-group
              = f.label :alias, class: 'label-main text-small'
              = f.text_field :alias, class: 'form-control form-color-main'
            .form-group
              = f.submit '保存', class: 'btn btn-main'

app/views/categories/index.html.slim
main.parent-category-main
  .category-info-area
    h2.text-huge.text-navy Engineer
    p.description こちらのページは、エンジニアのノウハウを中心に紹介しています。入門から実践を兼ね備えた情報を発信していきます。

  section
    .children-category-area
      p.text-huge Ruby on Rails

      .children-category-articles
        = link_to '/a/a/1' do
          .related-article
            img[src="https://images.unsplash.com/photo-1529101091764-c3526daf38fe?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=43ef07555334a21b6c7dcecc929070ce&auto=format&fit=crop&w=1782&q=80"]
            h3.title title

        = link_to '/a/a/1' do
          .related-article
            img[src="https://images.unsplash.com/photo-1529101091764-c3526daf38fe?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=43ef07555334a21b6c7dcecc929070ce&auto=format&fit=crop&w=1782&q=80"]
            h3.title title

        = link_to '/a/a/1' do
          .related-article
            img[src="https://images.unsplash.com/photo-1529101091764-c3526daf38fe?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=43ef07555334a21b6c7dcecc929070ce&auto=format&fit=crop&w=1782&q=80"]
            h3.title title


  aside
    == render partial: 'partials/sidebar'